name: settings
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  animations: ^2.0.7

  cupertino_icons: ^1.0.2

  dahlia_shared:
    git: https://github.com/dahliaos/shared
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  provider: ^6.0.5
  yatl_flutter:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl_flutter

dev_dependencies:
  lint: ^2.0.1

flutter:
  uses-material-design: true
